# Generated by Django 3.2.9 on 2021-11-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='variation_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
